### ISSUE TITLE
Unable to find string literal

### ISSUE THREAD

**Issue by dylib** [Marentis/znc-timer#1]
I tried to build this and ran into some issues:
```
Building "alarm.so" for ZNC 1.6.5... alarm.cpp:75:30: warning: ‘get_start_time’ function uses ‘auto’ type specifier without trailing return type [enabled by default]
     auto get_start_time  ( ) const
                              ^
alarm.cpp:79:27: warning: ‘get_end_time’ function uses ‘auto’ type specifier without trailing return type [enabled by default]
     auto get_end_time ( ) const
                           ^
alarm.cpp:87:24: warning: ‘get_timer’ function uses ‘auto’ type specifier without trailing return type [enabled by default]
     auto get_timer ( ) const
                        ^
alarm.cpp:91:21: warning: ‘get_id’ function uses ‘auto’ type specifier without trailing return type [enabled by default]
     auto get_id ( ) const
                     ^
alarm.cpp:103:22: error: unable to find string literal operator ‘operator"" s’
     string reason_ = "Default"s;
```
The error I changed to:
```
 string reason_ = "Default";
```
(the warnings I left because didn't know what to do)

The module was able to build after removing the `s` off the end, and I could load it with `/znc loadmod alarm`, although upon trying `/znc *alarm add` or `/znc *alarm list` it completely crashed `znc`.

**Comment by Marentis** [comment]
Oh god, somebody is actually using it, I never expected that tbh and it really is an ugly hackish thing. Then again, I'll probably update it within the next days to be less of a catastrophe. 
Regarding your compile issues:
I just tried if it compiles and it does so on znc 1.6.3 with the "-std=c++14" flag set in znc-buildmod without warnings. I've used -Wall, -Wextra and -Werror as compile flags. 
The gcc version being used is 6.2.0. 

Can you please post your CXXFLAGS from /usr/bin/znc-buildmod?

Regarding the crash issue upon issuing "list":
I just tried it and on my znc version and it doesn't crash. Which version are you using?

**Comment by dylib** [comment]
heheh, yes — I like your idea, and thanks for responding. 

current znc-buildmod `CXXFLAGS`:
```
CXXFLAGS="  -DOPENSSL_NO_COMP=1 -std=c++11 -D_FORTIFY_SOURCE=2 -O2 -Wall -W -Wno-unused-parameter -Woverloaded-virtual -Wshadow -pthread   -fvisibility=hidden -fPIC -include znc/zncconfig.h -I/usr/local/include $CXXFLAGS"
MODLINK="-shared $MODLINK"
VERSION="1.6.5"
```
ZNC Version `1.65`
GCC Version `gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-11)`

I used `-std=c++1y` (since my gcc is older) and I still get the error:
```
Building "alarm.so" for ZNC 1.6.5... alarm.cpp:105:22: error: unable to find string literal operator ‘operator"" s’
     string reason_ = "Default"s;
```
Once I change that to `string reason_ = "Default";` it compiles with no errors or warnings.

`/znc *alarm list` seems to work:
```
*alarm There are no timers running at the moment.
```
However, `/znc *alarm add` completely crashes `znc` to the ground. 

I'm not sure where logs for `znc` are stored for such events, but I'm happy to provide whatever info you might need to get this working, thanks!

**Comment by Marentis** [comment]
It seems that your compiler (c++ lib implementation) is too old to support string literals. 

I still wonder why it crashes as I don't have that issue on my odroid (arm based) and on my development machine (amd64). I'll try to obtain your exact znc version and see if I can figure something out. 

I'll report back and sorry for the delay in my answer. 

Update:
it seems that there's indeed an issue with znc 1.6.5 and this module. Looking further into it. 
Interestingly it crashes on my odroid but not on my amd64 based Ubuntu and Arch installations.
Will report back.

Update 2: I could verify that the thread for checking if a timer expired doesn't get created on my odroid platform while it does get created on my other platforms.

**Comment by dylib** [comment]
That is strange; I can only imagine that thread is off forking somewhere else. 😜

**Comment by Marentis** [comment]
Closed because I just tried it on my odroid after using the newest image (Ubuntu 16.04 with kernel 4.9.44 and znc 1.6.5) and it seems to work there now, too. Please feel free to tell me if the issue still persists.
